# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5929d72d45bd8e938cf0db926c03228604f36ea1dfa907a436a1a6bfb43bc45bd5463d9e4161827e7bb3759675308404759bef4b42b5614abe1e595aa3303213

test:
  secret_key_base: abf66068ab34dead69dca508801058ff9042357d5619ecab1af138df42396c0b8b84cb9ba80de72e863bc45c419ad5f7a75f606a51d1a1098f2373901d264c1d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
